# Generated by Django 4.2.8 on 2024-03-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Feet')], default='m', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=3),
        ),
    ]
