# Generated by Django 4.2.8 on 2024-03-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_height_alter_profile_height_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Feet')], default='cm', max_length=3),
        ),
    ]
