# Generated by Django 4.2.8 on 2024-03-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_height_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inches',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
