# Generated by Django 4.2.8 on 2024-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_tdee_profile_tdee_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='m', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
